// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Models.DBModels;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.DBModels.History", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Invoice")
                        .HasColumnType("character varying")
                        .HasColumnName("invoice")
                        .HasComment("если действие по инвойсу то id инвойса");

                    b.Property<string>("TypeHistory")
                        .HasColumnType("character varying")
                        .HasColumnName("type_history")
                        .HasComment("user_edited\r\ninvoice_edited");

                    b.Property<string>("UserEditor")
                        .HasColumnType("character varying")
                        .HasColumnName("user_editor")
                        .HasComment("Пользователь который совершил действие");

                    b.ToTable("history", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<bool?>("AutoProlongation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("auto_prolongation")
                        .HasDefaultValueSql("false")
                        .HasComment("автопролонгация, если указан true - то при оплате за этот инвойс автоматом создается след запись в табилице графика платежей");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance")
                        .HasComment("сумма баланса, если сумма в минусе то долг.\r\nСумма указывается в тыйынах");

                    b.Property<string>("Client")
                        .HasColumnType("character varying")
                        .HasColumnName("client");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateStartInvoice")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_start_invoice")
                        .HasComment("Дата начал инвойса, т.е с этого дня будет учитываться платеж");

                    b.Property<decimal?>("FixedSumm")
                        .HasColumnType("numeric")
                        .HasColumnName("fixed_summ")
                        .HasComment("фиксированная сумма платежа, если не указан или 0 то сумма для платежа любая сумма");

                    b.Property<bool>("Hassameaccount")
                        .HasColumnType("boolean")
                        .HasColumnName("hassameaccount")
                        .HasComment("если true - то это есть еще другой счет с таким же лицевым счетом и у которых общий баланс");

                    b.Property<string>("InvoiceStatus")
                        .HasColumnType("character varying")
                        .HasColumnName("invoice_status")
                        .HasComment("actual\r\nsuspended\r\nclosed");

                    b.Property<string>("NameInvoice")
                        .HasColumnType("character varying")
                        .HasColumnName("name_invoice");

                    b.Property<DateTime?>("NextStartInvoice")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_start_invoice")
                        .HasComment("Дата начала следующего периода инвойса, если автопролонгация или инвойс установлен на несколько периодов");

                    b.Property<string>("PayCode")
                        .HasColumnType("character varying")
                        .HasColumnName("pay_code");

                    b.Property<string>("Periodicity")
                        .HasColumnType("character varying")
                        .HasColumnName("periodicity")
                        .HasComment("периодичность оплаты:\r\ndaily - ежедневно\r\nweekly - еженедельно\r\nmonthly - ежемесячно\r\nyearly - ежегодно\r\nесли указывается конкретное число то значит каждые указанное число дней. \r\nт.е если к примеру 30 то каждые 30 дней.\r\noneTime - однаразовый и прием в любой момент\r\nany - прием в любой момент");

                    b.Property<string>("UserCreater")
                        .HasColumnType("character varying")
                        .HasColumnName("user_creater");

                    b.HasKey("Id")
                        .HasName("invoice_pk");

                    b.HasIndex("Client");

                    b.HasIndex("UserCreater");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.InvoicePayment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_from");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_to");

                    b.Property<string>("Invoice")
                        .HasColumnType("character varying")
                        .HasColumnName("invoice");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("character varying")
                        .HasColumnName("payment_status")
                        .HasComment("paid - уже оплатил\r\nnon_paid - еще не оплатил\r\nanulated - в таком случае д\\с возвращается обратно на баланс по инвойсу");

                    b.Property<string>("PaymentSumm")
                        .HasColumnType("character varying")
                        .HasColumnName("payment_summ")
                        .HasComment("сумма оплаты");

                    b.Property<string>("PeriodValue")
                        .HasColumnType("character varying")
                        .HasColumnName("period_value")
                        .HasComment("какой месяц или год\r\nесли периодичность месяц или год");

                    b.HasKey("Id")
                        .HasName("invoice_payments_pk");

                    b.HasIndex("Invoice");

                    b.ToTable("invoice_payments", null, t =>
                        {
                            t.HasComment("записи - за какие периоды оплачены");
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.InvoiceService", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Invoice")
                        .HasColumnType("character varying")
                        .HasColumnName("invoice");

                    b.Property<string>("Service")
                        .HasColumnType("character varying")
                        .HasColumnName("service");

                    b.Property<decimal?>("ServiceSumm")
                        .HasColumnType("numeric")
                        .HasColumnName("service_summ")
                        .HasComment("стоимость сервиса");

                    b.HasKey("Id")
                        .HasName("invoice_services_pk");

                    b.HasIndex("Invoice");

                    b.HasIndex("Service");

                    b.ToTable("invoice_services", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .HasColumnType("character varying")
                        .HasColumnName("channel")
                        .HasComment("email, telegram, whatsapp");

                    b.Property<string>("ClientId")
                        .HasColumnType("character varying")
                        .HasColumnName("client_id");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("character varying")
                        .HasColumnName("contact_info")
                        .HasComment("email, телефон, telegram chat_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<int?>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("retry_count")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'new'")
                        .HasComment("new - новое, ожидает обработки\r\nprocessing - в процессе обработки\r\nsent - отправлено\r\nfailed - ошибка отправки");

                    b.Property<string>("Subject")
                        .HasColumnType("character varying")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("notifications_pk");

                    b.HasIndex("ClientId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<bool>("AllowedHassameaccount")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed_hassameaccount")
                        .HasComment("если true - то организации могут создавать счета к оплате с одинаковыми л\\с");

                    b.Property<string>("ApiLogin")
                        .HasColumnType("character varying")
                        .HasColumnName("api_login")
                        .HasComment("Логин для API");

                    b.Property<string>("ApiPassword")
                        .HasColumnType("character varying")
                        .HasColumnName("api_password");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Organizationtype")
                        .HasColumnType("character varying")
                        .HasColumnName("organizationtype")
                        .HasComment("standart\r\ndetsad\r\nschool\r\nmedclinic");

                    b.Property<int>("Paymentreminderdaysbefore")
                        .HasColumnType("integer")
                        .HasColumnName("paymentreminderdaysbefore")
                        .HasComment("Количество дней за которую будет начинатся отправка уведомлений по оплате на организацию");

                    b.HasKey("Id")
                        .HasName("organization_pk");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationClient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("ClientAdres")
                        .HasColumnType("character varying")
                        .HasColumnName("client_adres");

                    b.Property<decimal?>("ClientBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("client_balance")
                        .HasComment("баланс в тыйынах");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("character varying")
                        .HasColumnName("client_email");

                    b.Property<string>("ClientInn")
                        .HasColumnType("character varying")
                        .HasColumnName("client_inn");

                    b.Property<string>("ClientLogo")
                        .HasColumnType("character varying")
                        .HasColumnName("client_logo");

                    b.Property<string>("ClientName")
                        .HasColumnType("character varying")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("character varying")
                        .HasColumnName("client_phone");

                    b.Property<int?>("ClientStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_status")
                        .HasDefaultValueSql("0")
                        .HasComment("0\\1");

                    b.Property<string>("ClinetType")
                        .HasColumnType("character varying")
                        .HasColumnName("clinet_type")
                        .HasComment("fiz\\jur");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Organization")
                        .HasColumnType("character varying")
                        .HasColumnName("organization");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UserCreater")
                        .HasColumnType("character varying")
                        .HasColumnName("user_creater");

                    b.HasKey("Id")
                        .HasName("organization_cients_pk");

                    b.HasIndex("Organization");

                    b.HasIndex("UserCreater");

                    b.ToTable("organization_clients", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationClientsAdditionalField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Field")
                        .HasColumnType("character varying")
                        .HasColumnName("field")
                        .HasComment("ссылка на organization_fields");

                    b.Property<string>("OrganizationClient")
                        .HasColumnType("character varying")
                        .HasColumnName("organization_client")
                        .HasComment("ссылка на клиента");

                    b.Property<string>("Value")
                        .HasColumnType("character varying")
                        .HasColumnName("value")
                        .HasComment("значение переменной\\поля");

                    b.HasKey("Id")
                        .HasName("organization_clients_additional_fields_pk");

                    b.HasIndex("Field");

                    b.HasIndex("OrganizationClient");

                    b.ToTable("organization_clients_additional_fields", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("FieldName")
                        .HasColumnType("character varying")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldSelectValues")
                        .HasColumnType("character varying")
                        .HasColumnName("field_select_values")
                        .HasComment("варианты для выбора чз - ;");

                    b.Property<string>("FieldType")
                        .HasColumnType("character varying")
                        .HasColumnName("field_type")
                        .HasComment("int\r\nstring\r\nmoney\r\nselected\r\ndatetime");

                    b.Property<bool?>("Filterbyfield")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("filterbyfield")
                        .HasDefaultValueSql("false");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Organization")
                        .HasColumnType("character varying")
                        .HasColumnName("organization");

                    b.HasKey("Id")
                        .HasName("organization_fields_pk");

                    b.HasIndex("Organization");

                    b.ToTable("organization_fields", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationService", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<int?>("FixedSum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fixed_sum")
                        .HasDefaultValueSql("0")
                        .HasComment("если 1 то услуга с фиксированной суммой");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("MaxSumm")
                        .HasColumnType("numeric")
                        .HasColumnName("max_summ")
                        .HasComment("макс сумма в тыйынах");

                    b.Property<decimal?>("MinSumm")
                        .HasColumnType("numeric")
                        .HasColumnName("min_summ")
                        .HasComment("мин сумма в тыйынах");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasColumnType("character varying")
                        .HasColumnName("organization");

                    b.Property<decimal?>("ServiceSumm")
                        .HasColumnType("numeric")
                        .HasColumnName("service_summ")
                        .HasComment("если fixed_sum = 1, то тут будет значение фиксированной суммы");

                    b.HasKey("Id")
                        .HasName("organization_services_pk");

                    b.HasIndex("Organization");

                    b.ToTable("organization_services", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasColumnType("character varying")
                        .HasColumnName("area");

                    b.Property<string>("Category")
                        .HasColumnType("character varying")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex(new[] { "Area" }, "idx_permissions_area");

                    b.HasIndex(new[] { "Category" }, "idx_permissions_category");

                    b.HasIndex(new[] { "Code" }, "idx_permissions_code");

                    b.HasIndex(new[] { "Isdeleted" }, "idx_permissions_isdeleted");

                    b.HasIndex(new[] { "Code" }, "permissions_code_key")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("AvilableServices")
                        .HasColumnType("character varying")
                        .HasColumnName("avilable_services")
                        .HasComment("перечисляется id сервисов чз ;");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasColumnType("character varying")
                        .HasColumnName("organization");

                    b.Property<string>("Rights")
                        .HasColumnType("character varying")
                        .HasColumnName("rights")
                        .HasComment("права пользователей");

                    b.HasKey("Id")
                        .HasName("roles_pk");

                    b.HasIndex(new[] { "Organization" }, "idx_roles_organization");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.RolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Permission")
                        .HasColumnType("character varying")
                        .HasColumnName("permission");

                    b.Property<string>("Role")
                        .HasColumnType("character varying")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("role_permissions_pkey");

                    b.HasIndex(new[] { "Isdeleted" }, "idx_role_permissions_isdeleted");

                    b.HasIndex(new[] { "Permission" }, "idx_role_permissions_permission");

                    b.HasIndex(new[] { "Role" }, "idx_role_permissions_role");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<string>("Invoice")
                        .HasColumnType("character varying")
                        .HasColumnName("invoice");

                    b.Property<decimal?>("Summ")
                        .HasColumnType("numeric")
                        .HasColumnName("summ")
                        .HasComment("сумма в тыйынах");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionStatus")
                        .HasColumnType("character varying")
                        .HasColumnName("transaction_status")
                        .HasComment("success\r\nerror");

                    b.Property<decimal?>("TransactionSumm")
                        .HasColumnType("numeric")
                        .HasColumnName("transaction_summ")
                        .HasComment("сумма транзакции в тыйынах вмесе с комиссией");

                    b.Property<string>("TransactionType")
                        .HasColumnType("character varying")
                        .HasColumnName("transaction_type")
                        .HasComment("debit - приход\r\ncredit - расход");

                    b.HasKey("Id")
                        .HasName("transactions_pk");

                    b.HasIndex("Invoice");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<int?>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasDefaultValueSql("false");

                    b.Property<string>("GoogleEmail")
                        .HasColumnType("character varying")
                        .HasColumnName("google_email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("character varying")
                        .HasColumnName("google_id");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasColumnType("character varying")
                        .HasColumnName("organization");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasColumnType("character varying")
                        .HasColumnName("role")
                        .HasComment("user\r\nadmin\r\nsuperadmin");

                    b.Property<string>("TwoFactorCode")
                        .HasColumnType("character varying")
                        .HasColumnName("two_factor_code");

                    b.Property<DateTime?>("TwoFactorCodeExpire")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("two_factor_code_expire");

                    b.Property<bool?>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled")
                        .HasDefaultValueSql("false");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("character varying")
                        .HasColumnName("two_factor_secret");

                    b.Property<string>("TwoFactorType")
                        .HasColumnType("character varying")
                        .HasColumnName("two_factor_type");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.HasIndex("Organization");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<int?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Role")
                        .HasColumnType("character varying")
                        .HasColumnName("role");

                    b.Property<string>("User")
                        .HasColumnType("character varying")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("user_roles_pk");

                    b.HasIndex("Role");

                    b.HasIndex("User");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Invoice", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.OrganizationClient", "ClientNavigation")
                        .WithMany("Invoices")
                        .HasForeignKey("Client")
                        .HasConstraintName("invoice_fk_1");

                    b.HasOne("WebApplication1.Models.DBModels.User", "UserCreaterNavigation")
                        .WithMany("Invoices")
                        .HasForeignKey("UserCreater")
                        .HasConstraintName("invoice_fk");

                    b.Navigation("ClientNavigation");

                    b.Navigation("UserCreaterNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.InvoicePayment", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Invoice", "InvoiceNavigation")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("Invoice")
                        .HasConstraintName("invoice_payments_fk");

                    b.Navigation("InvoiceNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.InvoiceService", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Invoice", "InvoiceNavigation")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("Invoice")
                        .HasConstraintName("invoice_services_fk");

                    b.HasOne("WebApplication1.Models.DBModels.OrganizationService", "ServiceNavigation")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("Service")
                        .HasConstraintName("invoice_services_fk_1");

                    b.Navigation("InvoiceNavigation");

                    b.Navigation("ServiceNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Notification", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.OrganizationClient", "ClientNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("notifications_fk");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationClient", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Organization", "OrganizationNavigation")
                        .WithMany("OrganizationClients")
                        .HasForeignKey("Organization")
                        .HasConstraintName("organization_clients_fk");

                    b.HasOne("WebApplication1.Models.DBModels.User", "UserCreaterNavigation")
                        .WithMany("OrganizationClients")
                        .HasForeignKey("UserCreater")
                        .HasConstraintName("organization_clients_fk2");

                    b.Navigation("OrganizationNavigation");

                    b.Navigation("UserCreaterNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationClientsAdditionalField", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.OrganizationField", "FieldNavigation")
                        .WithMany("OrganizationClientsAdditionalFields")
                        .HasForeignKey("Field")
                        .HasConstraintName("organization_clients_additional_fields_fk");

                    b.HasOne("WebApplication1.Models.DBModels.OrganizationClient", "OrganizationClientNavigation")
                        .WithMany("OrganizationClientsAdditionalFields")
                        .HasForeignKey("OrganizationClient")
                        .HasConstraintName("organization_clients_additional_fields_fk_1");

                    b.Navigation("FieldNavigation");

                    b.Navigation("OrganizationClientNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationField", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Organization", "OrganizationNavigation")
                        .WithMany("OrganizationFields")
                        .HasForeignKey("Organization")
                        .HasConstraintName("organization_fields_fk");

                    b.Navigation("OrganizationNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationService", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Organization", "OrganizationNavigation")
                        .WithMany("OrganizationServices")
                        .HasForeignKey("Organization")
                        .HasConstraintName("organization_services_fk");

                    b.Navigation("OrganizationNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Role", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Organization", "OrganizationNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("Organization")
                        .HasConstraintName("roles_fk_organization");

                    b.Navigation("OrganizationNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.RolePermission", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Permission", "PermissionNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("Permission")
                        .HasConstraintName("role_permissions_fk_1");

                    b.HasOne("WebApplication1.Models.DBModels.Role", "RoleNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("Role")
                        .HasConstraintName("role_permissions_fk");

                    b.Navigation("PermissionNavigation");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Transaction", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Invoice", "InvoiceNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("Invoice")
                        .HasConstraintName("transactions_fk");

                    b.Navigation("InvoiceNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.User", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Organization", "OrganizationNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Organization")
                        .HasConstraintName("users_fk");

                    b.Navigation("OrganizationNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.UserRole", b =>
                {
                    b.HasOne("WebApplication1.Models.DBModels.Role", "RoleNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("Role")
                        .HasConstraintName("user_roles_fk_1");

                    b.HasOne("WebApplication1.Models.DBModels.User", "UserNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("User")
                        .HasConstraintName("user_roles_fk");

                    b.Navigation("RoleNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Invoice", b =>
                {
                    b.Navigation("InvoicePayments");

                    b.Navigation("InvoiceServices");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Organization", b =>
                {
                    b.Navigation("OrganizationClients");

                    b.Navigation("OrganizationFields");

                    b.Navigation("OrganizationServices");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationClient", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Notifications");

                    b.Navigation("OrganizationClientsAdditionalFields");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationField", b =>
                {
                    b.Navigation("OrganizationClientsAdditionalFields");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.OrganizationService", b =>
                {
                    b.Navigation("InvoiceServices");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebApplication1.Models.DBModels.User", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrganizationClients");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
