//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Resources
{
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebApplication1.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string RememberMe
        {
            get
            {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }

        public static string SignIn
        {
            get
            {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }

        public static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        public static string Roles
        {
            get
            {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }

        public static string Permissions
        {
            get
            {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }

        public static string AssignRoles
        {
            get
            {
                return ResourceManager.GetString("AssignRoles", resourceCulture);
            }
        }

        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        public static string Actions
        {
            get
            {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        public static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        public static string ManagePermissions
        {
            get
            {
                return ResourceManager.GetString("ManagePermissions", resourceCulture);
            }
        }

        public static string SelectOrganization
        {
            get
            {
                return ResourceManager.GetString("SelectOrganization", resourceCulture);
            }
        }

        public static string PermissionsForOrganization
        {
            get
            {
                return ResourceManager.GetString("PermissionsForOrganization", resourceCulture);
            }
        }

        public static string SelectRoles
        {
            get
            {
                return ResourceManager.GetString("SelectRoles", resourceCulture);
            }
        }

        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        public static string Code
        {
            get
            {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        public static string Area
        {
            get
            {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }

        public static string GeneralPermission
        {
            get
            {
                return ResourceManager.GetString("GeneralPermission", resourceCulture);
            }
        }

        public static string SelectArea
        {
            get
            {
                return ResourceManager.GetString("SelectArea", resourceCulture);
            }
        }

        public static string Organization
        {
            get
            {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }

        public static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
    }
}

